apiVersion: v2
appVersion: "0.8.1"
description: Kubernetes native operator which fully manages Jenkins on Kubernetes
name: jenkins-operator
version: 0.8.1
icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png
dependencies:
- name: cert-manager
  version: "1.14.2"
  condition: cert-manager.enabled
  repository: https://charts.jetstack.io
- name: cert-manager-crds
  version: "1.14.2"
  condition: cert-manager.enabled
